id: P005546
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:58:39.144104
source_metadata:
  id: bdr:W8LS17232
  title: མདོ་སྡེ་བརྒྱད་བརྒྱ་པ།
  author: ''
  volumes:
    d52a9ee1ad5143c789401e8479d52910:
      image_group_id: I8LS17240
      title: ''
      volume_number: 1
      total_pages: 340
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
